Repository redhat-developer/openshift-jenkins-operator, pull requests merged in 2019-09, with the labels that each got.

#9 Refactoring: Use constants, generalise error handling
  go.mod
  pkg/controller/jenkins/controller.go
Labels: approved, size/M

#10 Add more constants
  pkg/controller/jenkins/controller.go
  pkg/controller/jenkins/reconciler.go
Labels: approved, size/M

#11 Put template for Unit Testing of reconciler.go in place with mocks
  pkg/apis/jenkins/v1alpha1/jenkins_types.go
  pkg/controller/jenkins/reconciler.go
  pkg/controller/jenkins/reconciler_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
Labels: approved, size/L

#12 Implements PVC creation
  go.mod
  pkg/controller/jenkins/controller.go
  pkg/controller/jenkins/reconciler.go
  pkg/controller/jenkins/reconciler_test.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/modules.txt
Labels: approved, size/XXL

#13 Various fixes
  pkg/controller/jenkins/reconciler.go
Labels: approved

#16 Unit Tests for reconciler.go
  pkg/controller/jenkins/reconciler.go
  pkg/controller/jenkins/reconciler_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#19 Add badge for master build on Quay.
  README.md
Labels: approved, lgtm, size/XS

#17 Update/template mvp
  manifests/jenkins-operator.v0.0.1.clusterserviceversion.yaml
  pkg/apis/addtoscheme_jenkins_v1alpha1.go
  pkg/controller/jenkins/controller.go
  pkg/controller/jenkins/reconciler.go
  pkg/controller/jenkins/reconciler_test.go
  test/mocks/mocks.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/openshift/api/authorization/v1/codec.go
  vendor/github.com/openshift/api/authorization/v1/doc.go
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/register.go
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/pkg/serialization/serialization.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#22 Update readme
  README.md
Labels: approved, lgtm, size/XS

#25 Fix CSV to match clusteroperatorversion
  deploy/olm-catalog/openshift-jenkins-operator/openshift-jenkins-operator.package.yaml
Labels: approved, lgtm, size/XS

#26 fix-service-operator-source-to-match-image
  deploy/olm-catalog/openshift-jenkins-operator/0.0.1/openshift-jenkins-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#30 Remove Gabe and Adam from reviewers/approvers list
  OWNERS
Labels: approved, lgtm, size/XS

#31 Removing username reference in operator.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#24 Initial checkin of operator source definition
  Makefile
  jenkins-operator-source.yaml
Labels: approved, lgtm, size/S

#29 move to 0.0.2
  deploy/olm-catalog/openshift-jenkins-operator/openshift-jenkins-operator.package.yaml
  manifests/jenkins-operator.package.yaml
  manifests/jenkins-operator.v0.0.1.clusterserviceversion.yaml
  manifests/jenkins-operator.v0.0.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#36 Jenkins container memory usage
  pkg/controller/jenkins/reconciler.go
Labels: approved, lgtm, size/XS
