Repository redhat-developer/openshift-jenkins-operator, pull requests merged in 2019-10, with the labels that each got.

#38 Extend README file with commands to run Operator locally
  README.md
Labels: approved, lgtm, size/M

#32 Replace "placeholder" text displayed in UI
  manifests/jenkins-operator.v0.0.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#35 Refactor codebase, Add Error Management
  deploy/operator.yaml
  pkg/common/messages.go
  pkg/controller/jenkins/common.go
  pkg/controller/jenkins/controller.go
  pkg/controller/jenkins/new.go
  pkg/controller/jenkins/reconciler.go
  test/mocks/fake.go
Labels: approved, lgtm, size/XL

#47 Add ability to for setting persistence through CR (during installation)
  deploy/crds/jenkins_ephemeral_v1alpha1_jenkins_cr.yaml
  deploy/crds/jenkins_persistent_v1alpha1_jenkins_cr.yaml
  deploy/crds/jenkins_v1alpha1_jenkins_crd.yaml
  pkg/apis/jenkins/v1alpha1/jenkins_types.go
  pkg/apis/jenkins/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/jenkins/controller.go
  pkg/controller/jenkins/new.go
  pkg/controller/jenkins/reconciler.go
  pkg/controller/jenkins/reconciler_test.go
Labels: approved, lgtm, size/L

#46 Add oc new-app example to the README
  README.md
Labels: approved, lgtm, size/S

#34 Add Make target to create Jenkins instance
  Makefile
Labels: approved, lgtm, size/XS

#52 Fix: Reference ClusterRole in RoleBinding instead of Role
  pkg/controller/jenkins/new.go
Labels: approved, lgtm, size/XS
